"""add is_current and grading fields to cv_documents

Revision ID: ff664f278b66
Revises: d4e5f6a7b8c9
Create Date: 2026-07-17 15:30:10.207371
"""
from alembic import op
import sqlalchemy as sa


revision = 'ff664f278b66'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv_documents', sa.Column('is_current', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('cv_documents', sa.Column('grade_score', sa.Integer(), nullable=True))
    op.add_column('cv_documents', sa.Column('grade_feedback', sa.String(), nullable=True))
    op.add_column('cv_documents', sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cv_documents', sa.Column('grade_acknowledged', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_cv_documents_is_current'), 'cv_documents', ['is_current'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cv_documents_is_current'), table_name='cv_documents')
    op.drop_column('cv_documents', 'grade_acknowledged')
    op.drop_column('cv_documents', 'graded_at')
    op.drop_column('cv_documents', 'grade_feedback')
    op.drop_column('cv_documents', 'grade_score')
    op.drop_column('cv_documents', 'is_current')
    # ### end Alembic commands ###
